import type { NextPage } from 'next'
import Head from 'next/head';
import Header from '../components/child/Header';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header title="hello"></Header>
        <h1>Hello Tracker</h1>
      </main>
    </>
  );
};

export default Home
