import type { NextPage } from 'next'
import Head from 'next/head'
import TailwindCssNotification from '../components/utility-first/tailwind-css-notification';
import Clr from '../components/responsive/clr';
import RCard from '../components/responsive/r_card';
import FInput from '../components/utility-first/f-input';
import DButton from '../components/utility-first/d-button';
import HButton from '../components/utility-first/h-button';
import Button from '../components/utility-first/_button';
import Link from 'next/link';
import Navbar from '../components/layout/Navbar';

const Home: NextPage = () => {
  return (
    <>
       <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <RCard ></RCard>


   

      </main>
    </>
   
 )
}

export default Home
